service:
  name: dynamodb-backup-json
frameworkVersion: '2'
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  profile: ${env:PROFILE}
  lambdaHashingVersion: 20201221
  environment:
    DYNAMODB_TABLE: ${env:DYNAMO_TABLE}
functions:
  export:
    handler: handler.exportToJSON
  import:
    handler: handler.importFromJSON
