service:
  name: dynamodb-backup-json
frameworkVersion: '2'
plugins:
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  profile: aa
  lambdaHashingVersion: 20201221
functions:
  main:
    handler: handler.main
